### ISSUE TITLE
Figure out a rule of thumb for tensor arena size

### ISSUE THREAD

**Issue by eloquentarduino** [eloquentarduino/EloquentTinyML#11]

**Comment by maarten-pennings** [comment]
Thanks for the lib. Works great.

I was also puzzled when figuring out the arena size. I wrote my process down for my project.
See the section starting with `One of the configuration parameters for the interpreter is the TENSOR_ARENA_SIZE.` in my project https://github.com/maarten-pennings/MachineLearning/blob/main/rock-paper-scissors/rock-paper-scissors.ipynb

Maybe this helps.
