### ISSUE TITLE
has no member named 'probaToClass'

### ISSUE THREAD

**Issue by zeta0707** [eloquentarduino/EloquentTinyML#14]
I tried to run DigitsExample on ESP32 board, but I got below class error.
I installed EloquentTinyML 0.0.4 through library manager.

```
/home/zeta/Arduino/DigitsExample/DigitsExample.ino: In function 'void loop()':
DigitsExample:50:23: error: 'class Eloquent::TinyML::TfLite<64u, 10u, 8192u>' has no member named 'probaToClass'
     Serial.println(ml.probaToClass(y_pred));
                       ^
DigitsExample:52:23: error: 'class Eloquent::TinyML::TfLite<64u, 10u, 8192u>' has no member named 'predictClass'
     Serial.println(ml.predictClass(x_test));
                       ^
exit status 1

'class Eloquent::TinyML::TfLite<64u, 10u, 8192u>' has no member named 'probaToClass'
```

![Screenshot_20201225_133221](https://user-images.githubusercontent.com/10907395/103119186-acf9a980-46b5-11eb-840b-a94c0a6216a8.png)
![Screenshot_20201225_133412](https://user-images.githubusercontent.com/10907395/103119304-314c2c80-46b6-11eb-91bb-ffd990274a0b.png)

**Comment by eloquentarduino** [comment]
Please update to v0.0.5

**Comment by zeta0707** [comment]
Hi Eloquent,

Yes, I updated to v0.0.5, then issue was gone.
Thanks a lot!

**Comment by zeta0707** [comment]
Close since issue is fixed.
