### ISSUE TITLE
digits_model.py

### ISSUE THREAD

**Issue by rkuo2000** [eloquentarduino/EloquentTinyML#15]
I found the fix.

When running tinymlgen, optimize default is True, 
the generated model file is quite small and cause ESP32 keep aborting.

After I modify digits_model.py to set optimize = False, like below :
    c_code = port(model, variable_name='digits_model', pretty_print=True, optimize=False)
    with open('digits_model.h', 'w') as f:
        print(c_code, file=f)

My Arduino example [TinyML_Digit](https://github.com/rkuo2000/arduino/tree/master/examples/TinyML_Digit) are running on ESP32 now !

**Comment by rkuo2000** [comment]
After set Optimize=False to convert the model to ccode,
I can also run 28x28 MNIST model on ESP32 now
[TinyML_MNIST](https://github.com/rkuo2000/arduino/tree/master/examples/TinyML_MNIST)

**Comment by eloquentarduino** [comment]
Where did you find `optimize=True` in my tutorials? I already switched to `optimize=False` in the latest version of `tinymlgen`.

**Comment by rkuo2000** [comment]
https://eloquentarduino.github.io/2020/01/easy-tinyml-on-esp32-and-arduino/
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]  <-- this indicates it needs OPTIMIZED_FOR_SIZE

and

c_code = port(model, pretty_print=True)  <-- also in your digits_model.py 
print(c_code)

The above code did not specify optimize=False, 
and it will generate a very small code. (my tinymlgen is v0.2 which is the current version)

**Comment by eloquentarduino** [comment]
Thanks, I removed `converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE] ` from the post. 
`tinymlgen` version `0.3` switched to `optimize=False` by default

**Comment by rkuo2000** [comment]
Thanks for your great work !

**Comment by whubaichuan** [comment]
@eloquentarduino It seems that in 2.4.3 (the latest version currently on 2022.09.02), 

`c_code = port(model, pretty_print=True) <-- also in your digits_model.py
print(c_code)`

does not specify optimize=False,
and it will generate a very small code.

**Comment by eloquentarduino** [comment]
Optimization seems to break the exported code. For the moment I will default to `optimize=False`
