### ISSUE TITLE
update to recent tensorflow version

### ISSUE THREAD

**Issue by fazerlab** [eloquentarduino/EloquentTinyML#33]
I see that EloquentTinyML lib use a old version of Tensorflow lite. Is there some plan to upgrade to a new version?
Maybe a tutorial about upgrade.
Anyway this a great job. Thank you
Marco

**Comment by eloquentarduino** [comment]
I updated the library. Please install from Github since I didn't published on the Arduino Library Manager yet since I made a major update and need to test yet.
Report back if it works now or not please.

**Comment by fazerlab** [comment]
> I updated the library. Please install from Github since I didn't published on the Arduino Library Manager yet since I made a major update and need to test yet. Report back if it works now or not please.

I will install and try, Thank you very much!!

**Comment by shooorf** [comment]
@eloquentarduino latest tensorflow lite micro has 97 builtin operators in AllOpsResolver
Do you have any plans to upgrade EloquentTinyML to this new version?

**Comment by eloquentarduino** [comment]
Hi @shooorf , I have plans to upgrade the library.
Problem is, the last time I checked (December), TensorFlow for Microcontrollers was completely refactored and I was only able to find a build for the Arduino Nano. When I tried to compile for Arduino Rp2040, I got a compilation error. That was an easy fix. Then I compiled for Portenta. Another compilation error.

I don't have to knowledge nor the patience to patch every single board out there. If you can point me to a document on how to install the latest version of TLMicro that is cross-board, I will be happy to do the upgrade. Lots of users are awaiting for the LSTM operator, for example.
