### ISSUE TITLE
Fail: "cannot move location counter backwards"

### ISSUE THREAD

**Issue by iludis21** [eloquentarduino/EloquentTinyML#34]
Hello Simone,
I used your script to create TinyML models, which should recognize 96x96 grayscale images. In Python everything worked as well, model was created. Only compiling for Nano33 BLE in Arduino does not work. It breaks with the error message "linker_script.ld:138 cannot move location counter backwards (from 20fd4a70 to 2003fc00)".
Could you maybe help me further? I get the same error message when I try to compile the exported model from Teachable Machine to Nano 33 BLE.

**Comment by eloquentarduino** [comment]
Hi never encountered this error. Please share your Arduino sketch and possibly your Python script.

**Comment by iludis21** [comment]
[problem_011121.zip](https://github.com/eloquentarduino/EloquentTinyML/files/7455842/problem_011121.zip)
Here it is. Thanks in advance.

**Comment by iludis21** [comment]
[test1_0311.zip](https://github.com/eloquentarduino/EloquentTinyML/files/7469684/test1_0311.zip)
Hello Simone, the problem has been solved. It was beginner's mistake - model was badly made and way too big (28MB). Fixed and optimized to 1,3MB - now it works.
But I have another problem: the input data are int values between 0 and 255, but as output I want to have two float values. But your predict function predict(input, output) supports either int/int or float/float. Can you give me a hint here?

**Comment by eloquentarduino** [comment]
I will fix the library on this. For now, declare your input as float so you can use the float/float version of predict.

**Comment by iludis21** [comment]
Thank you.

**Comment by coachD24** [comment]
> [test1_0311.zip](https://github.com/eloquentarduino/EloquentTinyML/files/7469684/test1_0311.zip) Hello Simone, the problem has been solved. It was beginner's mistake - model was badly made and way too big (28MB). Fixed and optimized to 1,3MB - now it works. But I have another problem: the input data are int values between 0 and 255, but as output I want to have two float values. But your predict function predict(input, output) supports either int/int or float/float. Can you give me a hint here?

Hi, I have the same problem now but I dont know how to fix it because when I download my model from Teachable Machine its just too big, even tho I only have uploaded 3 pictures to the model.
How can I fix this?
