### ISSUE TITLE
Any help to use EloquentTinyML (ver.0.0.5) on platformio ?.

### ISSUE THREAD

**Issue by simcube** [eloquentarduino/EloquentTinyML#36]
I would appreciate receiving any help to update EloquentTinyML (ver. 0.0.5) on PlatformIO. The DigitsExample was not working on PlatformIO with old version of  EloquentTinyML (ver. 0.0.3).

**Comment by eloquentarduino** [comment]
ver 0.0.5 is deprecated. Can you install ver 2.4.0?

**Comment by simcube** [comment]
No. I could not install the ver 2.4.0, because the registry of PlatformIO only showed the ver 0.0.2 and ver 0.0.3 when I carried out libraries search with the key word as EloquentTinyML. Any version is ok if it can be compatible with PlatformIO. Thank you for your help in advance.

**Comment by eloquentarduino** [comment]
I will take a look if I can force an update into the PlatformIO registry.
