### ISSUE TITLE
NameError: name 'Exp' is not defined

### ISSUE THREAD

**Issue by chisu7917** [eloquentarduino/EloquentTinyML#40]
NameError                                 Traceback (most recent call last)
[<ipython-input-13-8467977053e1>](https://localhost:8080/#) in <module>()
      1 if __name__ == '__main__':
----> 2     model, x_test, y_test = get_model()
      3     test_model(model, x_test, y_test)
      4     c_code = port(model, variable_name='digits_model', pretty_print=True)
      5     print(c_code)

[<ipython-input-11-10a9ef6cf51b>](https://localhost:8080/#) in get_model()
     16     model.fit(x_train, y_train, epochs=50, batch_size=16,
     17               validation_data=(x_validate, y_validate))
---> 18     return Exp
NameError: name 'Exp' is not defined

**Should I change 'return Exp' to 'reture model, x_test, y_test'**

Thank you!!

**Comment by eloquentarduino** [comment]
Yes, I guess my IDE autocomplete messed that line. I edited the file now.
