### ISSUE TITLE
Support for RNN (LSTM)

### ISSUE THREAD

**Issue by expeon07** [eloquentarduino/EloquentTinyML#44]
Hi, would you know if there is a way to implement RNN in TFLite micro? I use LSTM for time series prediction but I have this error. 

`Only 1 subgraph is currently supported.`

**Comment by dustinjoe** [comment]
I actually had the same question when I tried to run a LSTM model last summer for a paper submission:
https://github.com/dustinjoe/TinyML-with-Cloud-for-PHM
At that time, no official support for RNNs, I remember someone from Tensorflow team mentioned some memory issue.
But this time point, official LSTM support seems to be on the way right now:
https://github.com/tensorflow/tflite-micro/pull/1044

**Comment by eloquentarduino** [comment]
LSTM is indeed supported as many users reported. Be sure to use Tf==2.2.3

**Comment by whubaichuan** [comment]
@expeon07 @dustinjoe @eloquentarduino There is an operation called UnidirectionalSequenceLSTM in [the official library description](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/all_ops_resolver.cc). But I am not sure whether that's LSTM you want or not.
