### ISSUE TITLE
Files dependencies Arduino IDE 2.0.3 issue

### ISSUE THREAD

**Issue by slimoai** [eloquentarduino/EloquentTinyML#56]
Hi ! I am using Arduino IDE 2.0.3 and it seems the compiler is unable to find files dependency, the compiling went well on older Arduino IDE (I tested 1.8.x version)

..\Documents\Arduino\libraries\EloquentTinyML\src\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_1x1_HWC_q7_fast_nonsquare.c:1: fatal error: opening dependency file C:\Users\dell\AppData\Local\Temp\arduino-sketch-FE23B5A4229727714BC6CE307E63E40D\libraries\EloquentTinyML\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_1x1_HWC_q7_fast_nonsquare.c.d: No such file or directory
 #if !defined(ESP32)
 
compilation terminated.
..\Documents\Arduino\libraries\EloquentTinyML\src\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_HWC_q15_fast_nonsquare.c:1: fatal error: opening dependency file C:\Users\dell\AppData\Local\Temp\arduino-sketch-FE23B5A4229727714BC6CE307E63E40D\libraries\EloquentTinyML\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_HWC_q15_fast_nonsquare.c.d: No such file or directory
 #if !defined(ESP32)

**Comment by nonsintetic** [comment]
same issue as #37
