### ISSUE TITLE
FullyConnected Layers not Available in MutableTensorFlow

### ISSUE THREAD

**Issue by EClemMarq** [eloquentarduino/EloquentTinyML#61]
I am trying to reduce my resource usage using MutableTensorFlow.  However, I noticed that AddFullyConnected is currently commented out in MutableTensorFlow.h.

Could support please be added for these layers? 
https://github.com/eloquentarduino/EloquentTinyML/blame/af3a7bddde3e999836650f06e5e34686735089bd/src/eloquent_tinyml/tensorflow/common/MutableTensorFlow.h#L58

**Comment by eloquentarduino** [comment]
Moved to https://github.com/eloquentarduino/EloquentTensorFlow32
