### ISSUE TITLE
Compability Issues: Didn't find op for builtin opcode 'DEPTHWISE_CONV_2D' version '1' (Possibililty to integrate newer version?)

### ISSUE THREAD

**Issue by corusm** [eloquentarduino/EloquentTinyML#63]
Hi!,
I'm currently trying to run some [mobilenetv2](https://github.com/STMicroelectronics/stm32ai-modelzoo/tree/main) for object detection. But as already other threads shown, there are compability issues.

Is there an "easy" or rather straightforward way to integrate a new version of the library in here? Since I already say, that there is some CI from the tflight-micro library to the corresponding [espressif](https://github.com/espressif/tflite-micro-esp-examples/tree/master) repository.

I would really thank you for your support!

**Comment by eloquentarduino** [comment]
I moved the ESP32 part of this library to a new library: https://github.com/eloquentarduino/EloquentTensorFlow32
It relies on the Arduino_TensorFlow_ESP32 library, which you can update to the latest version. If that supports mobilenetv2, so will EloquentTensorFlow32. You have to try, I don't know.
