### ISSUE TITLE
Feature Request: Camera support for new Seeedstudio $14 XIAO-Esp32S3 

### ISSUE THREAD

**Issue by hpssjellis** [eloquentarduino/EloquentTinyML#65]
**Feature Request: Camera support for new Seeedstudio $14 XIAO-Esp32S3**

The sense module that it comes with has a camera and microphone.

[https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/](https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/)

The camera is a bit different than other esp32S3 and needs these definitions.

```
#include "esp_camera.h"
//#include "FS.h"
//#include "SD.h"
//#include "SPI.h"

//#define CAMERA_MODEL_XIAO_ESP32S3 // Has PSRAM


//#if defined(CAMERA_MODEL_XIAO_ESP32S3)
#define PWDN_GPIO_NUM     -1
#define RESET_GPIO_NUM    -1
#define XCLK_GPIO_NUM     10
#define SIOD_GPIO_NUM     40
#define SIOC_GPIO_NUM     39

#define Y9_GPIO_NUM       48
#define Y8_GPIO_NUM       11
#define Y7_GPIO_NUM       12
#define Y6_GPIO_NUM       14
#define Y5_GPIO_NUM       16
#define Y4_GPIO_NUM       18
#define Y3_GPIO_NUM       17
#define Y2_GPIO_NUM       15
#define VSYNC_GPIO_NUM    38
#define HREF_GPIO_NUM     47
#define PCLK_GPIO_NUM     13
```

From Jeremy Ellis

**Comment by eloquentarduino** [comment]
I moved the ESP32 part of this library to a new library: https://github.com/eloquentarduino/EloquentTensorFlow32
This library and the new one really don't make any assumption on the specific board you're using.
