### ISSUE TITLE
Feature request : ESP-NN in EloquentTinyML

### ISSUE THREAD

**Issue by slimoai** [eloquentarduino/EloquentTinyML#67]
Hello devs,

The ESP-NN* implementation on ESP32-S3 demonstrates a remarkable performance boost compared to the legacy ANSI-C version. With vector instructions, it can achieve up to 10 times better performance, depending on the neural network configuration. Are there any plans for potential integration into the excellent EloquentTinyML library in the future?

* : https://github.com/espressif/esp-nn

Cheers,

**Comment by eloquentarduino** [comment]
I "forked" the ESP32 part of this library to a new library of its own, because many users were getting ARM-related errors when developing for ESP32. 
Here is the library: https://github.com/eloquentarduino/EloquentTensorFlow32
It doesn't have ESP-NN at the moment, but I will add it there.

**Comment by asadm** [comment]
@eloquentarduino was esp-nn ever added? if not, any pointers on how does this need to happen. 

thanks for making this!

**Comment by eloquentarduino** [comment]
Frankly, I cannot find any hint on how to do this. I opened an issue on the esp-nn repo today, hope they will help me.
