### ISSUE TITLE
error message when using  Max Pool 2D

### ISSUE THREAD

**Issue by Roland75013** [eloquentarduino/EloquentTinyML#7]
Hello,
Thank you fir your library.
I have used your library to try to have an esp32 recognize handwriten digits (mnist 8x8), but I had an error message ""Didn't find op for builtin opcode 'MaxPool2D' version '2'". After some research,  I was able to find the problem, I had to modify line 25 in  all_ops_resolver.cpp

before
AddBuiltin(BuiltinOperator_MAX_POOL_2D, Register_MAX_POOL_2D();
after
AddBuiltin(BuiltinOperator_MAX_POOL_2D, Register_MAX_POOL_2D(), 1 , 2);

and now it works, no more  error message , and the esp32 is able to recognize handwriten digits.
Best Regards.

**Comment by eloquentarduino** [comment]
I appreciate you posted the solution to your own problem here, but I think this is not the appropriate topic. This library is just a wrapper to the Tensorflow library: it doesn't add any functionality to their code. You should probably post this issue on their repository.
Nevertheless, thank you for your effort.
