### ISSUE TITLE
Compilation Error with EloquentTinyML Library on ESP32 DevKit V1

### ISSUE THREAD

**Issue by srijan101** [eloquentarduino/EloquentTinyML#70]
Hello,

I am currently using the ESP32 DevKit V1 to upload my model, but I am encountering a persistent error stating “No Such File or Directory”. I have verified that the file does exist in the specified directory, yet the error persists.

I have attempted to resolve this issue by installing various versions of the EloquentTinyML library (ranging from 2.4.0 to 2.4.0), but to no avail. I have also tried manually downloading and installing the library from a zip file, but this has not resolved the issue.

The specific error messages I am receiving are as follows:

c:\Users\shrij\OneDrive\Documents\Arduino\libraries\EloquentTinyML\src\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_1x1_HWC_q7_fast_nonsquare.c:1: fatal error: opening dependency file C:\Users\shrij\AppData\Local\Temp\arduino\sketches\B053F9FA2E031EE44B13A1D119FFD475\libraries\EloquentTinyML\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_1x1_HWC_q7_fast_nonsquare.c.d: No such file or directory
#if !defined(ESP32)
compilation terminated.

c:\Users\shrij\OneDrive\Documents\Arduino\libraries\EloquentTinyML\src\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_HWC_q15_fast_nonsquare.c:1: fatal error: opening dependency file C:\Users\shrij\AppData\Local\Temp\arduino\sketches\B053F9FA2E031EE44B13A1D119FFD475\libraries\EloquentTinyML\eloquent_tinyml\tensorflow\arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_convolve_HWC_q15_fast_nonsquare.c.d: No such file or directory
#if !defined(ESP32)
compilation terminated

Any assistance in resolving this issue would be greatly appreciated.

Thank you.

**Comment by eloquentarduino** [comment]
Please migrate to my new library specifically for ESP32: https://github.com/eloquentarduino/EloquentTensorFlow32
